# Hammond catalog entries: (number, description, catalog page).
# Transcribed from the 1915 catalog's own Numerical Index (pp.7-11);
# entries marked "1920" are numbered beyond it and come from the 1920
# catalog. Data only - status is COMPUTED, see gen_catalog_index.py.
HAMMOND_CATALOG = [
    ('1', 'Medium Roman, Fractions, English, Ideal', '17'),
    ('2', 'Small Roman, Fractions, English, Ideal', '17'),
    ('3', 'Large Roman, Fractions, English, Ideal', '19'),
    ('3A', 'Large Roman, Fractions, English, Ideal', '19'),
    ('3B', 'Large Roman, Fractions, English, Ideal', '19'),
    ('4', 'Gothic, Fractions, English, Ideal', '19'),
    ('4A', 'Gothic, Spanish, Ideal', '28'),
    ('5', 'Caps and Small Caps, Fractions, English, Ideal', '19'),
    ('5A', 'Caps and Small Caps, Fractions, Spanish, Ideal', '27'),
    ('5B', 'Caps and Small Caps, Fractions, Spanish, Ideal', '28'),
    ('6', 'Italic, Fractions, English, Ideal', '20'),
    ('7', 'Greek, Ideal', '24'),
    ('8', 'Small Greek, four line, Ideal', '23'),
    ('9', 'Attic, Fractions, English, Ideal', '19'),
    ('10', 'Medium Roman, English, Ideal', '17'),
    ('10A', 'Medium Roman, English, Ideal', '18'),
    ('10B', 'Medium Roman, English, Ideal', '18'),
    ('11', 'Medium Roman, German, Ideal, Old Style', '21'),
    ('11A', 'Medium Roman, Dutch, Ideal', '16'),
    ('12', 'Large Roman, German, Ideal, Old Style', '21'),
    ('12A', 'Large Roman, Dutch, Ideal', '16'),
    ('12B', 'Large Roman, German, Ideal', '22'),
    ('12C', 'Large Roman, Croatian, Ideal', '16'),
    ('13', 'Italic, German, Ideal', '22'),
    ('13A', 'Italic, Dutch, Ideal', '17'),
    ('13B', 'Italic, German, Ideal', '22'),
    ('14', 'Medium Roman, French, Ideal', '20'),
    ('14A', 'Medium Roman, Italian, Ideal', '25'),
    ('15', 'Italic, French, Ideal', '21'),
    ('15A', 'Italic, Italian, Ideal', '25'),
    ('16', 'Medium Roman, Spanish, Ideal', '27'),
    ('16A', 'Medium Roman, Chilian, Ideal', '15'),
    ('16B', 'Medium Roman, Spanish, Ideal', '27'),
    ('17', 'Italic, Spanish, Ideal', '28'),
    ('17A', 'Italic, Chilian, Ideal', '15'),
    ('17B', 'Italic, Spanish, Ideal', '28'),
    ('18', 'Medium Roman, Medical, English, Ideal', '19'),
    ('19', 'Medium Roman, Diacritical, English, Ideal', '18'),
    ('20', 'German Text, Ideal', '23'),
    ('21', 'Medium Roman, English, Ideal', '18'),
    ('22', 'Medium Roman, Swedish-Finnish, Ideal', '29'),
    ('23', 'Medium Roman, English, Universal', '36'),
    ('23A', 'Medium Roman, English, Universal', '36'),
    ('23B', 'Medium Roman, English, Universal', '36'),
    ('23C', 'Medium Roman, English, Universal', '36'),
    ('23D', 'Medium Roman, English, Universal', '36'),
    ('23E', 'Medium Roman, English, Universal', '36'),
    ('23F', 'Medium Roman, English, Universal', '36'),
    ('23G', 'Medium Roman, English, Universal', '37'),
    ('24', 'Small Roman, English, Universal, Old Style', '35'),
    ('24A', 'Small Roman, English, Universal', '35'),
    ('24B', 'Small Roman, English, Universal', '35'),
    ('24C', 'Small Roman, English, Universal', '35'),
    ('24D', 'Small Roman, English, Universal', '36'),
    ('25', 'Large Roman, English, Universal', '37'),
    ('25A', 'Large Roman, English, Universal', '37'),
    ('25B', 'Large Roman, English, Universal', '37'),
    ('25C', 'Large Roman, English, Universal', '38'),
    ('26', 'Small Roman, Fractions, English, Universal', '36'),
    ('27', 'Caps and Small Caps, English, Universal', '38'),
    ('27A', 'Caps and Small Caps, Italian, Universal', '47'),
    ('27B', 'Caps and Small Caps, Italian, Universal', '47'),
    ('28', 'Law Italic, English, Universal', '39'),
    ('28A', 'Law Italic, Spanish, Universal', '51'),
    ('29', 'Large Russian, Universal', '49'),
    ('29A', 'Large Russian, Universal, Old Style', '49'),
    ('29B', 'Large Russian, Universal, Old Style', '50'),
    ('29C', 'Large Bulgarian, Universal', '32'),
    ('30', 'Medium Roman, Polish, Universal', '48'),
    ('31', 'Medium Roman, Russian, Universal', '49'),
    ('31A', 'Medium Roman, Russian, Universal', '49'),
    ('31B', 'Medium Roman, Russian, Universal', '49'),
    ('31C', 'Medium Roman, Bulgarian, Universal', '32'),
    ('32', 'Medium Roman, French, Universal', '40'),
    ('32A', 'Medium Roman, French, Universal', '40'),
    ('32B', 'Medium Roman, Italian, Universal', '46'),
    ('32C', 'Medium Roman, Roumanian, Universal', '49'),
    ('32D', 'Medium Roman, Roumanian, Universal', '49'),
    ('32E', 'Medium Roman, French, German, English, Universal', '41'),
    ('33', 'Medium Roman, Spanish, Universal', '51'),
    ('33A', 'Medium Roman, Chilian, Universal', '32'),
    ('33B', 'Medium Roman, Spanish, Universal (Mexican-Spanish Keyboard)', '51'),
    ('33C', 'Medium Roman, Spanish, Universal (Mexican-Spanish Keyboard)', '51'),
    ('33D', 'Spanish, French, English', '53'),
    ('34', 'Medium Roman, German, Universal', '42'),
    ('34A', 'Medium Roman, Dutch, Universal', '34'),
    ('34B', 'Medium Roman, Croatian, Universal', '33'),
    ('34C', 'Medium Roman, Fractions, German, Universal', '42'),
    ('34D', 'Medium Roman, Fractions, Dutch, Universal', '34'),
    ('34E', 'Lithuanian, English, German, Croatian', '53'),
    ('35', 'Italic, Russian, Ideal', '27'),
    ('35A', 'Italic, Bulgarian, Ideal', '15'),
    ('36', 'Small Roman, German, Ideal', '21'),
    ('36A', 'Small Roman, Dutch, Ideal', '16'),
    ('36B', 'Small Roman, German, Ideal (New Orthography)', '21'),
    ('37', 'Small Roman, English, Ideal', '17'),
    ('37A', 'Small Roman, English, Ideal', '17'),
    ('38', 'Medium Roman, Swedish-Finnish, Ideal', '29'),
    ('39', 'Large Roman, French, Special, Ideal', '21'),
    ('40', 'Medium Roman, Fractions, English, Universal', '37'),
    ('41', 'Small Roman, Fractions, English, Universal', '36'),
    ('42', 'Italic, Russian, Universal', '50'),
    ('42A', 'Italic, Russian, Universal', '50'),
    ('42C', 'Italic, Bulgarian, Universal', '32'),
    ('43', 'Medium Roman, Special Medical, English, Universal', '37'),
    ('43A', 'Medium Roman, Medical, English, Universal', '37'),
    ('44', 'Medium Roman, Hungarian, Ideal', '24'),
    ('45', 'Large Roman, Argentine Government, Ideal or Universal', '54'),
    ('46', 'Large Roman, Spanish, Ideal', '27'),
    ('46A', 'Large Roman, Chilian, Ideal', '15'),
    ('46B', 'Large Roman, Spanish, Ideal', '27'),
    ('47', 'Large Roman, Spanish, Universal', '51'),
    ('47A', 'Large Roman, Chilian, Universal', '33'),
    ('48', 'Medium Roman, Fractions, English, Ideal', '19'),
    ('48A', 'Medium Roman, Fractions, English, Ideal', '18'),
    ('48B', 'Medium Roman, Fractions, English, Ideal', '18'),
    ('48C', 'Medium Roman, Library, English, Ideal', '18'),
    ('49', 'Large Russian, Ideal', '26'),
    ('49A', 'Medium Bulgarian, Ideal', '15'),
    ('50', 'Large Roman, German, Universal', '43'),
    ('50A', 'Large Roman, Dutch, Universal', '34'),
    ('50B', 'Large Roman, Fractions, German, Universal', '43'),
    ('50C', 'Large Roman, Fractions, Dutch, Universal', '34'),
    ('51', 'Large Roman, English, Ideal', '19'),
    ('51A', 'Large Roman, English, Ideal', '19'),
    ('52', 'Large Roman, Fractions, English, Universal', '38'),
    ('53', 'Irish, Gaelic, Universal or Ideal', '55'),
    ('54', 'Medium Roman, Bohemian, Ideal', '14'),
    ('55', 'Medium Roman, Swedish-Finnish, Universal', '52'),
    ('55A', 'Medium Roman, Swedish-Finnish, Universal', '52'),
    ('55B', 'Medium Roman, Swedish-Finnish, Universal', '52'),
    ('55C', 'Medium Roman, Fractions, Swedish-Finnish, Universal', '52'),
    ('55D', 'Medium Roman, Danish-Norwegian, Universal', '33'),
    ('55E', 'Medium Roman, German, Universal (New Orthography)', '42'),
    ('55F', 'Medium Roman, Fractions, German, Universal (New Orthography)', '43'),
    ('56', 'Medium Roman, Hungarian, Universal, Old Style', '45'),
    ('57', 'Medium Roman, Hungarian, Ideal', '24'),
    ('58', 'Medium Roman, Croatian, Ideal', '16'),
    ('59', 'German Text, Universal', '43'),
    ('60', 'Gothic Italic, English, Ideal', '20'),
    ('60A', 'Gothic Italic, Spanish, Ideal', '28'),
    ('60B', 'Gothic Italic, Spanish, Ideal', '28'),
    ('61', 'Small Roman, French, Ideal', '20'),
    ('61A', 'Small Roman, Italian, Ideal', '24'),
    ('62', 'Large Roman, French, Ideal', '21'),
    ('62A', 'Large Roman, Italian, Ideal', '25'),
    ('63', 'Medium Roman, Portuguese, Ideal', '26'),
    ('63A', 'Medium Roman, Portuguese, Ideal', '26'),
    ('63B', 'Medium Roman, Portuguese, Ideal', '26'),
    ('64', 'Italic, Hungarian, Universal, Old Style', '46'),
    ('65', 'Small Roman, Spanish, Ideal', '27'),
    ('65A', 'Small Roman, Chilian, Ideal', '15'),
    ('65B', 'Small Roman, Spanish, Ideal', '27'),
    ('66', 'Small Roman, Spanish, Universal', '50'),
    ('66A', 'Small Roman, Chilian, Universal', '32'),
    ('66B', 'Small Roman, Spanish, Universal', '51'),
    ('67', 'Small Roman, French, Universal', '40'),
    ('67A', 'Small Roman, Italian, Universal', '46'),
    ('68', 'Italic, English, Universal', '39'),
    ('68A', 'Italic, Spanish, Universal', '51'),
    ('69', 'Large Roman, French, Universal', '41'),
    ('69A', 'Large Roman, Italian, Universal', '46'),
    ('70', 'Vertical Script, English, Ideal', '20'),
    ('71', 'Small Roman, German, Universal', '42'),
    ('71A', 'Small Roman, Dutch, Universal', '34'),
    ('71B', 'Small Roman, Croatian, Universal', '33'),
    ('71C', 'Small Roman, German, Universal (New Orthography)', '42'),
    ('71D', 'Small Roman, Fractions, German, Universal', '42'),
    ('71E', 'Small Roman, Fractions, German, Universal (New Orthography)', '42'),
    ('71F', 'Small Roman, Fractions, Dutch, Universal', '34'),
    ('73', 'Medium Roman, Italian, Universal', '46'),
    ('74', 'Gothic Italic, Hungarian, Ideal', '24'),
    ('75', 'Greek, Ideal', '24'),
    ('76', 'Gothic Italic, German, Ideal', '22'),
    ('76A', 'Gothic Italic, Dutch, Ideal', '16'),
    ('76B', 'Gothic Italic, German, Ideal', '22'),
    ('77', 'Medium Roman, Polish, Ideal', '25'),
    ('78', 'Vertical Script, German, Ideal', '23'),
    ('78A', 'Vertical Script, Dutch, Ideal', '17'),
    ('78B', 'Vertical Script, German, Ideal', '23'),
    ('79', 'Gothic Italic, French-German, Ideal', '21'),
    ('80', 'Vertical Script, English, Universal', '39'),
    ('80A', 'Vertical Script, Fractions, English, Universal', '39'),
    ('81', 'Armenian, Ideal or Universal', '54'),
    ('82', 'English Greek, four line, Ideal', '24'),
    ('83', 'Vertical Script, Spanish, Ideal', '28'),
    ('83A', 'Vertical Script, Chilian, Ideal', '16'),
    ('83B', 'Vertical Script, Spanish, Ideal', '28'),
    ('84', 'Vertical Script, German, Universal', '45'),
    ('84A', 'Vertical Script, Dutch, Universal', '35'),
    ('84B', 'Vertical Script, Fractions, German, Universal', '45'),
    ('84C', 'Vertical Script, Fractions, Dutch, Universal', '35'),
    ('85', 'Vertical Script, French, Universal', '41'),
    ('85A', 'Vertical Script, Italian, Universal', '47'),
    ('86', 'Medium Roman, Bohemian, Ideal', '14'),
    ('87', 'Medium Roman, Fractions, Danish, Ideal', '16'),
    ('88', 'Medium Roman, Danish, Ideal', '16'),
    ('89', 'Vertical Script, Spanish, Universal', '51'),
    ('89A', 'Vertical Script, Chilian, Universal', '33'),
    ('90', 'Italic, Swedish-Finnish, Universal', '53'),
    ('90A', 'Italic, Danish-Norwegian, Universal', '34'),
    ('91', 'Italic Script, German, Ideal', '22'),
    ('91A', 'Italic Script, Dutch, Ideal', '17'),
    ('91B', 'Italic Script, German, Ideal', '22'),
    ('92', 'Medium Roman, Roumanian, Ideal', '26'),
    ('93', 'Small Roman, Swedish-Finnish, Universal', '51'),
    ('93A', 'Small Roman, Swedish-Finnish, Universal', '52'),
    ('93B', 'Small Roman, Danish-Norwegian, Universal', '33'),
    ('94', 'Medium Roman, English, Ideal', '18'),
    ('95A', 'Hebrew-English, Ideal', '29'),
    ('96', 'Gothic, English, Universal', '38'),
    ('97', 'Gothic Italic, Fractions, English, Universal', '38'),
    ('97A', 'Gothic Italic, Roumanian, Universal', '49'),
    ('97B', 'Gothic Italic, English, Universal', '39'),
    ('98', 'Arabic, Ideal-Universal', '54'),
    ('100', 'Display Type, Ideal', '57'),
    ('101', 'Large Roman, Swedish-Finnish, Universal', '52'),
    ('101A', 'Large Roman, Swedish-Finnish, Universal', '52'),
    ('101B', 'Large Roman, Swedish-Finnish, Universal', '52'),
    ('101C', 'Large Roman, Danish-Norwegian, Universal', '33'),
    ('101D', 'Large Roman, German, Universal (New Orthography)', '43'),
    ('101E', 'Large Roman, Fractions, German, Universal (New Orthography)', '43'),
    ('102', 'Italic, German, Ideal', '23'),
    ('102A', 'Italic, German, Ideal', '23'),
    ('102B', 'Italic, Dutch, Ideal', '17'),
    ('103', 'Medium Roman, Portuguese, Universal', '48'),
    ('103A', 'Medium Roman, Portuguese, Universal', '48'),
    ('103B', 'Medium Roman, Portuguese, Universal', '48'),
    ('104', 'Italic, French, Universal', '41'),
    ('104A', 'Italic, French, Universal', '41'),
    ('104B', 'Italic, Italian, Universal', '47'),
    ('105', 'Small Roman, Esperanto, Ideal', '20'),
    ('106', 'Vertical Script, Portuguese, Ideal', '26'),
    ('107', 'Medium Roman, Chemical, English, Universal', '37'),
    ('108', 'Medium Roman, Chemical, French, Universal', '40'),
    ('108A', 'Medium Roman, Chemical, French, Universal', '40'),
    ('108B', 'Medium Roman, Chemical, Italian, Universal', '46'),
    ('109', 'Large Roman, Chemical, French, Universal', '41'),
    ('109A', 'Large Roman, Chemical, French, Universal', '41'),
    ('109B', 'Large Roman, Chemical, Italian, Universal', '46'),
    ('110', 'Small Roman, Chemical, French, Universal', '40'),
    ('110A', 'Small Roman, Chemical, French, Universal', '40'),
    ('110B', 'Small Roman, Chemical, Italian, Universal, Old Style', '46'),
    ('111', 'Vertical Script, French, Universal', '41'),
    ('111A', 'Vertical Script, French, Universal', '42'),
    ('111B', 'Vertical Script, Italian, Universal', '47'),
    ('112A', 'Greek, Universal', '45'),
    ('112B', 'Greek, Universal', '45'),
    ('113', 'Medium Roman, Library, English, Universal', '37'),
    ('114', 'Medium Roman, German, Ideal (New Orthography)', '21'),
    ('115', 'Large Italic, Russian, Universal', '50'),
    ('115A', 'Large Italic, Russian, Universal', '50'),
    ('115B', 'Large Italic, Russian, Universal', '50'),
    ('115C', 'Large Italic, Bulgarian, Universal', '32'),
    ('116', 'Medium Roman, Bohemian, Universal', '32'),
    ('117', 'Italic, German, Universal', '44'),
    ('117A', 'Italic, German, Universal', '44'),
    ('117B', 'Italic, Dutch, Universal', '35'),
    ('117C', 'Italic, Croatian, Universal', '33'),
    ('117D', 'Italic, German, Fractions, Universal (New Orthography)', '41'),
    ('117E', 'Italic, German, Fractions, Universal (New Orthography)', '44'),
    ('117F', 'Italic, Dutch, Universal', '35'),
    ('118', 'Law Italic, English, Ideal', '20'),
    ('119', 'Gothic Italic, German, Universal', '43'),
    ('119A', 'Gothic Italic, German, Universal', '44'),
    ('119B', 'Gothic Italic, Dutch, Universal', '34'),
    ('119C', 'Gothic Italic, Fractions, German, Universal (New Orthography)', '44'),
    ('119D', 'Gothic Italic, Fractions, German, Universal', '44'),
    ('119E', 'Gothic Italic, Dutch, Universal', '35'),
    ('120', 'Medium Roman, Bohemian, Ideal', '14'),
    ('121', 'Medium Roman, Polish-German, Ideal', '25'),
    ('122', 'Attic, Diacritical, English, Universal', '38'),
    ('123', 'Large Italic, German, Ideal', '23'),
    ('124', 'Large Italic, German, Universal (New Orthography)', '44'),
    ('125', 'Servian, Ideal', '27'),
    ('126', 'Servian, Universal', '50'),
    ('127', 'Braille, Ideal (for the Blind)', '15'),
    ('128', 'Braille, Universal (for the Blind)', '32'),
    ('131', 'Small Roman, Argentine Government, Universal or Ideal', '54'),
    ('133', 'Display Type, Universal', '57'),
    ('134', 'Large Gothic, English, Universal', '38'),
    ('134A', 'Large Gothic, Hungarian, Universal', '46'),
    ('134B', 'Large Gothic, Swedish-Finnish, Universal', '52'),
    ('134C', 'Large Gothic, Danish-Norwegian, Universal', '34'),
    ('134D', 'Large Gothic, German, Universal (New Orthography)', '43'),
    ('134E', 'Large Gothic, French, Universal', '41'),
    ('134F', 'Large Gothic, Italian, Universal, Old Style', '47'),
    ('135', 'Medium Roman, Mathematical, English, Universal', '47'),
    ('135A', 'Medium Roman, Esperanto, Universal', '40'),
    ('135B', 'Medium Roman, Mathematical, English, Universal', '48'),
    ('135C', 'Medium Roman, Mathematical, English, Universal', '48'),
    ('135D', 'Medium Roman, Esperanto, Universal', '40'),
    ('136', 'Special Gothic, English, Universal', '38'),
    ('137', 'Medium Roman, French (Belgian Keyboard), Ideal and Universal', '55'),
    ('138', 'Small Roman, French (Belgian Keyboard), Ideal and Universal', '54'),
    ('139', 'Italic, French (Belgian Keyboard), Ideal and Universal', '55'),
    ('140', 'Large Roman, French (Belgian Keyboard), Ideal and Universal', '55'),
    ('141', 'Large Roman, Polish, Universal', '48'),
    ('142', 'Medium Roman, Mathematical, English, Ideal', '25'),
    ('143', 'Large Roman, Russian, Universal', '50'),
    ('144', 'Multigraph (Pica), Spanish, Ideal', '28'),
    ('144A', 'Multigraph (Pica), English, Ideal', '20'),
    ('144B', 'Multigraph (Pica), German, Ideal', '23'),
    ('145', 'Multigraph (Pica), English, Universal', '39'),
    ('145A', 'Multigraph (Pica), German, Universal (New Orthography)', '45'),
    ('145B', 'Multigraph (Pica), French, Universal', '45'),
    ('150', 'Italic, Portuguese, Universal', '49'),
    ('150B', 'Italic, Italian, Universal', '47'),
    ('150C', 'Italic, Polish, Universal', '48'),
    ('151', 'Large Roman, Hungarian, Ideal', '24'),
    ('152', 'Small Roman, Hungarian, Ideal', '24'),
    ('153', 'Gothic, German, Ideal', '22'),
    ('153A', 'Gothic, German, Ideal (New Orthography)', '22'),
    ('153B', 'Gothic, Polish, Ideal', '26'),
    ('153C', 'Gothic, Bohemian, Ideal', '15'),
    ('154', 'Medium Roman, Polish, Ideal', '25'),
    ('154A', 'Medium Roman, Bohemian, Ideal', '14'),
    ('155', 'Small Roman, Polish, Ideal', '25'),
    ('155A', 'Small Roman, Bohemian, Ideal', '14'),
    ('156', 'Large Roman, Polish, Ideal', '26'),
    ('156A', 'Large Roman, Bohemian, Ideal', '14'),
    ('157', 'Italic, Polish, Ideal', '26'),
    ('157A', 'Italic, Bohemian, Ideal', '15'),
    ('158', 'Miniature Roman, English, Universal', '39'),
    ('158A', 'Miniature Roman, English, Universal', '39'),
    ('159', 'Small Roman, Portuguese, Universal', '48'),
    ('161', 'Bell Visible Speech Shuttle', '55'),
    ('162', 'Medium Gothic, English, Universal', '38'),
    ('165', 'English-Yiddish, Universal', '53'),
    ('166', 'Turkey-Persian, Ideal-Universal', '56'),
    ('167', 'Yiddish, Universal', '53'),
    ('168', 'Arabic, Ideal-Universal', '51'),
    ('169', 'Italic, English, Universal', '39'),
    ('170', 'Clarendon, English, Universal', '1920'),
    ('171', 'Arabic-Persian-Turkish', '55'),
    ('172', 'Dutch-German-French-English', '35'),
    ('179', 'Small Roman, Special Chemical, English, Universal', '1920'),
    ('180', 'Petite Gothic, English, Universal', '1920'),
    ('184', 'Gothic, Special Fractions, English, Universal', '1920'),
    ('185', 'Check Writer, Perforating, English, Universal', '1920'),
    ('192', 'Small Roman, Literary, English, Universal', '1920'),
    ('193', 'Medium Roman, Literary, English, Universal', '1920'),
    ('194', 'Small Italic, Literary, English, Universal', '1920'),
    ('195', 'Astronomical, Astrological, English, Universal', '1920'),
    ('196', 'International Phonetic, English, Universal', '1920'),
    ('197', 'International Phonetic Auxiliary, English, Universal', '1920'),
]
