"""
Mignon keyboard layout presets - 30 named layouts sharing one 7-row/
12-column physical layout (see blickensderfer_layout.py's note).
"""

# Mignon's 30 real named layouts from v2/lib/layouts/mignon_layouts.scad's
# Layouts=[] array (33 total minus 3 empty placeholders - CUSTOMLAYOUT,
# DEUTSCH_FRAKTUR_GOTISCH, DEUTSCH_FRAKTUR_PROF_STIEHL - all-empty-string
# rows in the real source, never finished/used there either). A few source
# rows had a 13th character v2 itself never reads (Char_Legend only ever
# indexes 0-11) - truncated to 12 to match what v2 actually uses (Georgian
# rows 2/4, Greek rows 3/4).
#
# Stored here in RAW KEYBOARD-LEGEND order - i.e. v2's own `Layout` array,
# exactly as printed on the physical keyboard/manual - NOT the Char_Legend-
# remapped `Physical_Layout` order used for actual glyph placement. The two
# differ by a fixed rotation: physical = keyboard[7:12] + keyboard[0:7]
# (Char_Legend=[7,8,9,10,11,0,1,2,3,4,5,6]), equivalently keyboard =
# physical[5:] + physical[:5] - the exact "move the first 5 characters to
# the end" transform the user asked for, applied once here to what used to
# be stored (physical order, from the original import) to reach the
# canonical keyboard-legend representation. mignon.py's configure() applies
# the Char_Legend remap itself when loading layout.rows into DHIATENSOR, so
# the actual built geometry is unchanged - only this display/edit
# representation moved to match what a person reads off the machine.
LAYOUT_PRESETS_MIGNON = {
    'English 2': [
        '\'"%&(£$);:,.',
        '?PFUGQpfugq¼',
        '!VINABvinab½',
        '_LDETMldetm¾',
        'JKOSRZkosrzj',
        '/YCHWXychwx@',
        '#1234567890-',
    ],
    'English 3': [
        '()&\'".,:¼½¾⅛',
        '?PFUGQpfugq⅜',
        '=VINABvinab⅝',
        '+LDETMldetm⅞',
        'JKOSRZkosrzj',
        '/YCHWXychwx_',
        '£23456789%@-',
    ],
    'English 4': [
        '()&\'".,:¼½¾⅛',
        '?PFUGQpfugq⅜',
        '=VINABvinab⅝',
        '$LDETMldetm⅞',
        'JKOSRZkosrzj',
        '/YCHWXychwx_',
        '£23456789%@-',
    ],
    'German 2': [
        '§%&():,.äöü¾',
        '"PFUGQpfugq½',
        '?VINABvinab¼',
        "_LDETMldetm'",
        'JKOSRZkosrzj',
        '/YCHWXychwx!',
        '„1234567890-',
    ],
    'German 4': [
        '&():"!?\'äöü_',
        '§PFUGQpfugq;',
        'JVINABvinabj',
        '/LDETMldetm,',
        '%KOSRZkosrz=',
        '¾YCHWXychwx+',
        '½¼23456789.-',
    ],
    'German-French': [
        '§%&():,.äöüè',
        '"PFUGQpfugqà',
        '?VINABvinabé',
        "_LDETMldetm'",
        'JKOSRZkosrzj',
        '/YCHWXychwxç',
        '^1234567890-',
    ],
    'Bohemian 3': [
        '!?´%23456789',
        'PFUGJpfugjů"',
        'VNIABvniabíá',
        'LDETMldetméě',
        'KOSRZkosrzšř',
        'YCHWXychwxžú',
        '&ˇ§Qqýč/,:.-',
    ],
    'Bulgarian': [
        '§ЮЯЛЦVюялць&',
        '№ПРХСУпрхсуй',
        '/ЩШКАМщшкам!',
        'ЗОВЪТѢовътѣз',
        '%ГИНЕДгинед?',
        'IЖФѪБЧжфѫбч"',
        '2456789.-,;:',
    ],
    'Cyrillic': [
        '§%№VI:"!,?=-',
        'ЂПФУГJпфугjђ',
        'ЧВИНАБвинабч',
        'ШЛДЕТМлдетмш',
        'ЋКОСРЗкосрзћ',
        'ЏЉЦХЊЖљцхњжџ',
        '/123456789._',
    ],
    'Danish 2': [
        'Æ§&?()_\'¨:"æ',
        'ØPFUGQpfugqø',
        'JVINABvinabj',
        '%LDETMldetm,',
        '/KOSRZkosrz÷',
        '¼YCHWXychwx+',
        '½¾23456789.-',
    ],
    'Danish 3': [
        'Æ§&?()_\'¨:"æ',
        'ØPFUGQpfugqø',
        'JVINABvinabj',
        '%LDETMldetm,',
        '/KOSRZkosrz÷',
        '¼YCHWXychwx+',
        '½¾23456789.=',
    ],
    'Esperanto': [
        '()23456789é"',
        "'PFUGQpfugq:",
        '!VINABvinab.',
        '?LDETMldetm,',
        'JKOSRZkosrzj',
        '^YCHWXychwx-',
        'ĴŜĈĤĜŬŝĉĥĝŭĵ',
    ],
    'French 3': [
        'K&()?:,"_çùk',
        'WJFQBYjfqbyw',
        '§VNIAPvniapà',
        "/DOUT'doutéè",
        '%CSERGcserg^',
        '½HLMZXhlmzx+',
        '¼23456789.-=',
    ],
    'Georgian': [
        '[]!":.,-;?*\'',
        'IV&წძცყქღჷა^',
        'XCგბეიულტჲ¨=',
        'LDჩუმდაႱზჱ§,',
        '$Mჴვროთხნჵჶ№',
        '£§ჰჭჟჯფპკ#ჳ/',
        '1234567890%½',
    ],
    "Greek (New Orthography)": [
        '£123456789-;',
        "&ΠΡΚΓΞπρκγξ'",
        '½ΛΤΗΑΒλτηαβ͂',
        '¼ΜΔΕΝΨμδενψ̇',
        '_ΘΟΥΙΖθουιζ.',
        '%ΧΩΣͅΦχωσϛφ,',
        '$()/„῟῞῏῎´᾿¨',
    ],
    'Dutch 2': [
        '&():"?\'¨`^´_',
        '£PFUGQpfugqĳ',
        'JVINABvinabj',
        '/LDETMldetm,',
        '%KOSRZkosrz+',
        '¾YCHWXychwx=',
        '½¼2345ƒ6789.',
    ],
    'Italian 3': [
        '"%&()^àèìòùé',
        '?WFUGQwfugq!',
        'JVINABvinabj',
        "_LDETMldetm'",
        '=KOSRZkosrz,',
        '/YCHPXychpx:',
        '+º23456789.-',
    ],
    'Croatian-Slovenian': [
        '%+=_:,.!?"-´',
        '&PFUGKpfugkć',
        'QVINAJvinajq',
        'ĐLDETMldetmđ',
        '§ČOSŠZčosšz/',
        'WBCHRŽbchržw',
        'YX23456789xy',
    ],
    'Latvian': [
        '32ļģŗņķ?!=/̦',
        '4PFUGCpfugc"',
        '5VINABvinab-',
        '6LDETMldetm,',
        '7KOSRZkosrz.',
        '8HJX%§hjxāūē',
        '9ČŠŽ()čšžī:̄',
    ],
    'Lithuanian': [
        "!'23456789;-",
        'ŲPFUGĄpfugąų',
        'ĮVINABvinabį',
        ',LDETMldetm?',
        '_KOSĘZkosęz/',
        '.YCHRJychrj"',
        '%ŽĖŠČŪžėščū§',
    ],
    'Polish 2': [
        '?§&óśńźćąę\'"',
        '%PFUGQpfugq!',
        'ŻVINABvinabż',
        'ŁLDETMldetmł',
        'JKOSRZkosrzj',
        '/YCHWXychwx,',
        '|:23456789.-',
    ],
    'Portuguese 2': [
        '&?Ç!º̃áéêóç#',
        '%PFUGQpfugq£',
        ':VINABvinab$',
        '(LDETMldetm)',
        'JKOSRZkosrzj',
        "'YCHWXychwx,",
        '"/23456789.-',
    ],
    'Romanian 1': [
        '§W()"?w\';:!_',
        '&KFOMHkfomhî',
        '/DCESBdcesbș',
        '=GPARUgparuă',
        '+LTINVltinvț',
        '%YXJZQyxjzqâ',
        '½23456789,.-',
    ],
    "Russian (New Orthography)": [
        '№ХЬЯЛУхьялу!',
        '1ТГСЮЙтгсюй/',
        '2РПОИЫрпоиы"',
        '3ЧВЕНДчвендз',
        "4ЦАМКБцамкб'",
        '5ЖЩШЭФжщшэф.',
        '6789%$£§/,:-',
    ],
    'Russian 3': [
        'ЭХЯЛЬГэхяльг',
        'ОПРСЮУпрсюуо',
        'IЩШЧТНщшчтнi',
        'ЗФЦКАЕфцкаез',
        '2БИМВДбимвд?',
        '4ЖЙЫЪѢжйыъѣ!',
        '56789№§.-:,/',
    ],
    'Spanish-American': [
        '&?¿!¡;áéíóúñ',
        '%PFUGQpfugq£',
        ':VINABvinab$',
        '(LDETMldetm)',
        'JKOSRZkosrzj',
        "'YCHWXychwx,",
        '"/23456789.-',
    ],
    'International Script': [
        '123456789-,_',
        '&PFUGQpfugq.',
        'JVINABvinabj',
        '=LDETMldetmé',
        '%KOSRZkosrzç',
        '/YCHWXychwx:',
        '§!?()"´`^ˇ˚˜',
    ],
    'Swedish 2': [
        '§()ÄÖ:"\',äö+',
        'QPFUGÅpfugåq',
        '?VINABvinab=',
        '&LDETMldetm_',
        '%KOSRJkosrj.',
        'XYCHWZychwzx',
        '/¼½¾23456789',
    ],
    'Ukrainian': [
        'ҐХЯЛЬГґхяльг',
        "%ПРСЮУпрсюу'",
        'IЩШЧТНщшчтнi',
        '2ФЦКАЕфцкае?',
        'ЗБИМВДбимвдз',
        '4ЖОЙЄЇжойєї!',
        '56789№§.-:,/',
    ],
    'Hungarian 2': [
        '?:!"ÖÜ,űőöüú',
        'ÉPFUGYpfugyé',
        'ÓVINABvinabó',
        'ÁLDETMldetmá',
        'JKOSRZkosrzj',
        '/QCHWXqchwx.',
        '+%23456789§-',
    ],
}
